version: '3.8'
services:
  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DB_HOST=database
      - EVENTSTORE_HOST=eventstore
    expose:
      - 4000
      - 4001
    ports:
      - 4000:4000
    depends_on:
      - database
      - eventstore
    networks:
      - backend
  eventstore:
    container_name: eventstore
    image: eventstore/eventstore:latest
    expose:
      - '2113'
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - eventstore:/var/lib/eventstore
    networks:
      - backend
  nginx:
    build:
      context: ./nginx/deploy
      dockerfile: Dockerfile
    ports:
      - '443:80'
    networks:
      - backend
    depends_on:
      - nestjs
    restart: always
  database:
    container_name: database
    image: postgres:latest
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
volumes:
  eventstore:
  postgres:
